#!/bin/bash
die() {
    echo "$1" 1>&2
    exit 1
}

path="$(readlink -f "$1")"
name="$2"
[ -d "$path" ] || die "Not a directory: $path"
url="http://wormhole:7117/project/$path"
[ -n "$name" ] && url="$url?name=$name"
curl -f "$url"
